version = 1

[[analyzers]]
name = "php"
enabled = true

  [analyzers.meta]
  php_version = "8.2"

  [analyzers.bootstrap]
  run = [
    "composer install",
    "cp .env.example .env",
    "php artisan key:generate"
  ]

[[analyzers]]
name = "javascript"
