version = 1

[[analyzers]]
name = "php"
enabled = true

  [analyzers.bootstrap]
  run = [
    "composer install --no-interaction --prefer-dist",
    "cp .env.example .env",
    "php artisan key:generate"
  ]

[[analyzers]]
name = "javascript"
